name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.1'

    - name: Install dependencies
      run: |
        pip install -r builder/requirements.txt
        pip install pytest pytest-asyncio

    - name: Run tests
      run: pytest

    - name: Build Docker image
      run: docker build -t dougmagno/scalable-microservice:latest .

    - name: Push Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push dougmagno/scalable-microservice:latest

    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v4
      with:
        manifests: |
          k8s/deployment.yaml
          k8s/service.yaml
          k8s/ingress.yaml
        images: dougmagno/scalable-microservice:latest
        kubectl-version: 'latest'
        namespace: default
